### ISSUE TITLE
[Question/Request] Help needed in implementing similar functionality in EZ Maintenance tool

### ISSUE THREAD

**Issue by OfficerKD637** [Protomove/Core-remove-kodi#1]
Hi!

Hope you're doing well!

This is a wonderful tool and achieves exactly what I wanted for so long. Although, there was supposed to be a PR in the main Kodi branch that would not create core dump files on webOS when debug logging was disabled, I could never get that to work (even tried disabling it in advancedsettings and the GUI)

But this plugin is amazing!

So I had a request regarding helping me adding the same functionality in the EZ Maintenance plugin.

I think this part of your code is where the magic happens:

```
def delete_core_files():
    home_path = translatePath('special://xbmc')
    dialog = xbmcgui.Dialog()

    # Verificar si el directorio existe
    if os.path.exists(home_path):
        file_count = 0
        # Obtener la lista de archivos en el directorio principal
        files = [f for f in os.listdir(home_path) if os.path.isfile(os.path.join(home_path, f))]
        # Contar los archivos cuyos nombres empiezan con "core."
        file_count += sum(1 for f in files if f.startswith("core."))

        if file_count > 0:
            for f in files:
                try:
                    if f.startswith("core."):
                        os.unlink(os.path.join(home_path, f))
                except Exception as e:
                    xbmcgui.Dialog().notification('Error', str(e))
            xbmcgui.Dialog().notification('Limpia Tu Kodi', "Archivos core eliminados correctamente")
        else:
            xbmcgui.Dialog().notification('Limpia Tu Kodi', "No se encontraron archivos core")
    else:
        xbmcgui.Dialog().notification('Error', "El directorio home no fue encontrado")
```

And this is where you can find the plugin: https://peno64.github.io/repository.peno64/

Can you help me with which file I need to change so I can also delete core files when using this plugin?

Would really mean a lot if you could help me modify this with your code.

Thank you!

**Comment by montes70** [comment]
def delete_core_files():
    home_path = translatePath('special://xbmc')
    dialog = xbmcgui.Dialog()

    # Verificar si el directorio existe
    if os.path.exists(home_path):
        file_count = 0
        # Obtener la lista de archivos en el directorio principal
        files = [f for f in os.listdir(home_path) if os.path.isfile(os.path.join(home_path, f))]
        # Contar los archivos cuyos nombres empiezan con "core."
        file_count += sum(1 for f in files if f.startswith("core."))

        if file_count > 0:
            for f in files:
                try:
                    if f.startswith("core."):
                        os.unlink(os.path.join(home_path, f))
                except Exception as e:
                    xbmcgui.Dialog().notification('Error', str(e))
            xbmcgui.Dialog().notification('Limpia Tu Kodi', "Archivos core eliminados correctamente")
        else:
            xbmcgui.Dialog().notification('Limpia Tu Kodi', "No se encontraron archivos core")
    else:
        xbmcgui.Dialog().notification('Error', "El directorio home no fue encontrado")
